### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by linus** [supabase/doctest-js#121]
Running `npm run build` has two issues:

```
[webpack-cli] Unknown argument: -p
```

And:

```
[webpack-cli] Compilation finished
assets by status 1.52 KiB [cached] 1 asset
./src/index.js 39 bytes [built] [code generated] [1 error]

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/linus.thiel/development/linus/doctest-js/node_modules/babel-preset-es2015/lib/index.js
    at createDescriptor (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at /Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-chain.js:384:26)
    at /Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-chain.js:347:7
    at Generator.next (<anonymous>)
    at buildRootChain (/Users/linus.thiel/development/linus/doctest-js/node_modules/@babel/core/lib/config/config-chain.js:129:29)
```

Expected result:

Build succeeds and a new file is produced in `dist/index.js`.

**Comment by linus** [comment]
Mistakenly closed by merging a PR in fork linus/doctest-js -- reopening.
